version: '3'

services:
  db:
    image:  docker.io/mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysqsl/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"