version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - './postgresql_data:/bitnami/postgresql'
      # - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  gitea:
    image: docker.io/bitnami/gitea:1
    volumes:
      - './gitea_data:/bitnami/gitea'
      # - 'gitea_data:/bitnami/gitea'
    environment:
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
      - GITEA_ADMIN_USER=admin
      - GITEA_ADMIN_PASSWORD=password
      - GITEA_ADMIN_EMAIL=a@a.com
    ports:
      - '3000:3000'
      - '2222:2222'
# volumes:
  # postgresql_data:
  #   driver: local
  # gitea_data:
  #   driver: local


  # default user:bn_user
  # default password:bitnami